local fixture=dofile('tests/action_fixture.lua')
local reader=dofile('src/action_reader.lua')
local base=dofile('src/context_reader.lua')
local backend=dofile('src/action_backend.lua')
local controller=dofile('src/action_controller.lua')
local passed=0
local function equal(a,b) assert(a==b,tostring(a)..' ~= '..tostring(b)) end
local function test(name,f)
    local ok,err=pcall(f);assert(ok,name..': '..tostring(err))
    passed=passed+1;print('PASS '..name)
end
local function make(ammo_path)
    local s=fixture(ammo_path)
    s.backend=backend.new(s.api,reader,base,s.layout,s.bind)
    s.events={}
    s.controller=controller.new(s.backend,function(kind,fields)
        if s.log_failure then return false end
        s.events[#s.events+1]={kind=kind,fields=fields};return true
    end)
    function s.step(now,action,armed,allowed,mouse)
        s.controller.step(armed~=false,now,{deploy=action=='DEPLOY' or action=='BOTH',
            detonate=action=='DETONATE' or action=='BOTH',allowed=allowed~=false,mouse=mouse})
    end
    function s.count(kind)
        local n=0;for _,r in ipairs(s.events) do if r.kind==kind then n=n+1 end end;return n
    end
    return s
end
test('live descriptor and type match authorize a fresh C4 capability',function()
    local s=make();local row,_,cap=s.snap()
    equal(row.current_fire_mode,'DEPLOY');equal(row.ammo_available,4)
    equal(cap.active,false);equal(cap.blocked,false);assert(cap.same())
end)
test('Deploy while selected Detonate preserves mode and calls full original consumption sequence',function()
    local s=make();s.u32(0x4b000000+16,256)
    s.step(0);s.step(20,'DEPLOY')
    equal(#s.calls,4);equal(s.calls[1][2],521)
    equal(s.calls[2][1],'consume');equal(s.calls[3][1],'count');equal(s.calls[4][1],'after')
    equal(s.calls[4][2],4);equal(s.snap().current_fire_mode,'DETONATE')
    equal(s.snap().ammo_available,3);equal(s.count('action_started'),1)
end)
test('Detonate in Deploy mode with zero backpack ammo calls only lifecycle 520',function()
    local s=make();s.u32(s.counter_state,0)
    s.step(0);s.step(20,'DETONATE')
    equal(#s.calls,1);equal(s.calls[1][2],520);equal(s.snap().current_fire_mode,'DEPLOY')
end)
test('empty Deploy never borrows deployed-charge display count or calls native mutation',function()
    local s=make();s.u32(s.counter_state,0);s.step(0);s.step(20,'DEPLOY')
    equal(#s.calls,0);equal(s.count('action_rejected'),1)
end)
test('unsupported descriptors and function types prevent all actions',function()
    local s=make();s.u32(s.templates+256,522);s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
    s=make();s.u32(0x4a000000+0x3e0+0x340,11);s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
end)
test('unsupported ammo path retains C4 identity, flags and exact rejection without a capability',function()
    local s=make();s.u32(s.driver_state,0x88);s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
    local row,reason,cap=s.snap()
    equal(reason,nil);equal(cap,nil);equal(row.current_weapon,'C4_DETONATOR')
    equal(row.current_fire_mode,'DEPLOY');equal(row.weapon_driver_flags,'00000088')
    equal(row.action_context_status,'rejected');equal(row.action_read_stage,'weapon_driver')
    equal(row.action_context_error,'unsupported_c4_ammo_path')
    equal(s.events[#s.events].fields.reason,'unsupported_c4_ammo_path')
end)
test('WeaponRounds supports Deploy across modes through the same four original calls',function()
    local s=make('rounds');s.u32(0x4b000000+16,256)
    local row,_,cap=s.snap()
    equal(row.ammo_path,'weapon_rounds');equal(row.rounds_config_source,'resource_template')
    equal(row.rounds_chambered,true);equal(row.rounds_chamber_token,54)
    equal(cap.deploy_ready,true);assert(cap.same())
    s.step(0);s.step(20,'DEPLOY');equal(#s.calls,4);equal(s.calls[1][2],521)
    equal(s.snap().current_fire_mode,'DETONATE');equal(s.snap().rounds_magazine_count,3)
end)
test('empty magazine with a ready chamber still admits the native last round',function()
    local s=make('rounds');s.u32(s.rounds_state+4,0)
    equal(s.snap().ammo_available,0);equal(s.snap().deploy_ammo_ready,true)
    s.step(0);s.step(20,'DEPLOY');equal(#s.calls,4)
    s.complete();s.step(100,'DEPLOY');equal(#s.calls,4)
    equal(s.snap().deploy_ammo_ready,false)
end)
test('empty or blocked chamber denies Deploy even with magazine rounds; Detonate stays independent',function()
    for _,blocked in ipairs({false,true}) do
        local s=make('rounds')
        if blocked then s.put(s.rounds_runtime+0x10,'\1') else s.u32(s.rounds_state+0x10,0) end
        equal(s.snap().rounds_magazine_count,4);equal(s.snap().deploy_ammo_ready,false)
        s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
        equal(s.events[#s.events].fields.reason,blocked and 'rounds_chamber_blocked' or 'rounds_chamber_empty')
        s.step(40,'DETONATE');equal(#s.calls,1);equal(s.calls[1][2],520)
    end
end)
test('non-chambered rounds use selected magazine signed count, never unrelated chamber state',function()
    for _,n in ipairs({0,1,0xffffffff,0x80000000}) do
        local s=make('rounds');s.put(s.rounds_config+0x68,'\0');s.u32(s.rounds_runtime+4,1)
        s.u32(s.rounds_state+8,n);s.u32(s.rounds_state+0x10,0);s.put(s.rounds_runtime+0x10,'\1')
        local row,_,cap=s.snap();equal(row.ammo_available,n);equal(cap.deploy_ready,n==1)
        s.step(0);s.step(20,'DEPLOY');equal(#s.calls,n==1 and 4 or 0)
    end
end)
test('rounds settings honor entity override before resource template',function()
    local s=make('rounds');s.map(s.rounds+0x68,s.rounds_override_map,{{s.wid,1}})
    local settings=s.allocate();s.ptr(s.rounds+0xa8,settings);s.zero(settings+0x84,0x84)
    s.u32(s.rounds_state+0x10,0)
    local row,_,cap=s.snap();equal(row.rounds_config_source,'entity_override')
    equal(row.rounds_chambered,false);equal(cap.deploy_ready,true)
    s.put(settings+0x84+0x68,'\1')
    equal(cap.same(),false);equal(s.snap().deploy_ammo_ready,false)
end)
test('native ammo branch priority selects rounds even if resource and heat flags are also set',function()
    local s=make('rounds');s.u32(s.driver_state,0x708);s.memory[s.resource_state]=nil
    equal(s.snap().ammo_path,'weapon_rounds');s.step(0);s.step(20,'DEPLOY');equal(#s.calls,4)
    s=make('rounds');s.u32(s.driver_state,0x188)
    local row,_,cap=s.snap();equal(row.ammo_path,'weapon_magazine');equal(cap,nil)
end)
test('missing configuration, invalid selected magazine and mismatched component cannot authorize actions',function()
    for _,kind in ipairs({'config','slot','registry'}) do
        local s=make('rounds')
        if kind=='config' then s.zero(s.rounds_templates+43*16,16)
        elseif kind=='slot' then s.u32(s.rounds_runtime+4,2)
        else s.ptr(s.rounds+0x40,0x12340000) end
        local row,_,cap=s.snap();equal(cap,nil);equal(row.weapon_driver_flags,'00000108')
        equal(row.action_context_status,'rejected');s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
    end
end)
test('resource hash table collision wraps using all 64 hash bits',function()
    local s=make('rounds');s.zero(s.rounds_templates+43*16,16)
    for slot=43,45 do s.put(s.rounds_templates+slot*16,'\1\0\0\0\0\0\0\0') end
    s.put(s.rounds_templates,'\61\47\245\33\99\13\245\81')
    local row,_,cap=s.snap();equal(row.rounds_config_source,'resource_template');equal(cap.deploy_ready,true)
end)
test('snapshot instability invalidates even a retained action diagnostic',function()
    local s=make('rounds');s.u32(s.rounds_runtime+4,2)
    local n=0
    s.intercept=function(at,size)
        if at==s.driver_state then
            n=n+1
            if n==2 then return string.rep('\0',size),true end
        end
    end
    local row,reason,cap=s.snap();equal(row,nil);equal(reason,'context_changed_during_read');equal(cap,nil)
end)
test('ability registry must refer to the exact selected owned entity',function()
    local s=make();s.put(s.waddr+20,'\0');s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
    s=make();s.ptr(s.ability+0x30,0x12340000);s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
end)
test('native block and exclusion bits deny requests',function()
    for _,mutate in ipairs({function(s) s.u32(s.blocker_state+0x19c,2) end,
        function(s) s.u32(s.exclusion_state,1) end,function(s) s.u32(s.exclusion_state,8) end,
        function(s) s.u32(s.exclusion_state,32) end,function(s) s.u32(s.exclusion_state,4) end}) do
        local s=make();mutate(s);s.step(0);s.step(20,'DETONATE');equal(#s.calls,0)
    end
end)
test('native paired exclusion bits preserve original allowance',function()
    local s=make();s.u32(s.exclusion_state,1+2+8+16+32+64)
    s.step(0);s.step(20,'DEPLOY');equal(#s.calls,4)
end)
test('outside grounded avatar scope and original Fire state deny test keys',function()
    local s=make();s.u32(s.avatar_flags,0);s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
    s=make();s.put(s.fire_state,'\1');s.step(0);s.step(20,'DEPLOY');equal(#s.calls,0)
end)
test('arming cannot execute a simultaneously held test key',function()
    local s=make();s.step(0,'DEPLOY');equal(#s.calls,0)
    s.step(20);s.step(40,'DEPLOY');equal(#s.calls,4)
end)
test('preexisting native action is neither restarted nor queued behind',function()
    local s=make();s.put(s.ability_state+0x10,'\1');s.u32(s.ability_state,521)
    s.step(0);s.step(20,'DETONATE');equal(#s.calls,0);equal(s.controller.pending,nil)
end)
test('one pending action coalesces repeated requests and waits for native completion',function()
    local s=make();s.step(0);s.step(20,'DEPLOY');s.step(40,'DETONATE')
    for t=60,200,20 do s.step(t,'DETONATE') end
    equal(#s.calls,4);equal(s.count('action_queued'),1)
    s.complete();s.step(300);equal(#s.calls,5);equal(s.calls[5][2],520)
    equal(s.count('action_finished'),1);equal(s.controller.pending,nil)
end)
test('pending remains bounded while native weapon is temporarily blocked by own action',function()
    local s=make();s.step(0);s.step(20,'DEPLOY');s.u32(s.exclusion_state,4)
    s.step(40,'DETONATE');s.step(60,'DEPLOY');equal(s.controller.pending.action,'DETONATE')
    equal(#s.calls,4);s.u32(s.exclusion_state,0);s.complete();s.step(200);equal(#s.calls,5)
end)
local function pending_during_refill()
    local s=make('rounds')
    s.u32(s.rounds_state+4,0)
    s.step(0);s.step(20,'DEPLOY');s.step(40,'DEPLOY')
    equal(#s.calls,4);equal(s.controller.pending.action,'DEPLOY')
    s.complete();s.step(100)
    return s
end
test('queued Deploy survives native completion until the real chamber becomes ready',function()
    local s=pending_during_refill()
    equal(s.controller.lock,nil);equal(s.controller.pending.action,'DEPLOY')
    equal(s.count('pending_waiting'),1);equal(s.count('action_rejected'),0)
    for t=200,400,100 do s.step(t) end
    equal(#s.calls,4);equal(s.count('pending_waiting'),1)
    s.u32(s.rounds_state+0x10,55);s.put(s.rounds_runtime+0x10,'\0');s.step(500)
    equal(#s.calls,8);equal(s.controller.pending,nil);equal(s.calls[5][2],521)
end)
test('repeat requests during refill neither grow the pending slot nor refresh its deadline',function()
    local s=pending_during_refill()
    s.step(200,'DEPLOY');s.step(400,'DETONATE')
    equal(s.controller.pending.action,'DEPLOY');equal(s.controller.pending.at,40)
    equal(s.count('action_queued'),1);equal(s.count('action_rejected'),2);equal(#s.calls,4)
    s.step(1600);equal(s.controller.pending,nil)
    s.u32(s.rounds_state+0x10,55);s.put(s.rounds_runtime+0x10,'\0');s.step(1700)
    equal(#s.calls,4)
end)
test('weapon switch, focus, disarm, mouse and failed context also clear a refill-waiting request',function()
    for _,kind in ipairs({'weapon','focus','capture','mouse','read'}) do
        local s=pending_during_refill()
        if kind=='weapon' then s.u32(s.state+0x1c,1)
        elseif kind=='read' then s.memory[s.rounds_state]=nil end
        s.step(200,nil,kind~='capture',kind~='focus',kind=='mouse')
        equal(s.controller.pending,nil);equal(#s.calls,4)
    end
end)
test('native action replacement and native exclusion cancel a refill-waiting request',function()
    for _,kind in ipairs({'action','exclusion'}) do
        local s=pending_during_refill()
        if kind=='action' then s.u32(s.ability_state,600);s.put(s.ability_state+0x10,'\1')
        else s.u32(s.exclusion_state,4) end
        s.step(200);equal(s.controller.pending,nil);equal(#s.calls,4)
    end
end)
test('an empty chamber without a transient refill flag is rejected rather than retained',function()
    local s=pending_during_refill();s.put(s.rounds_runtime+0x10,'\0');s.step(200)
    equal(s.controller.pending,nil);equal(#s.calls,4)
    equal(s.events[#s.events].fields.reason,'rounds_chamber_empty')
end)
test('native completion is not inferred from delay and timeout cannot reset an active action',function()
    local s=make();s.step(0);s.step(20,'DEPLOY');s.step(40,'DETONATE');s.step(9000)
    equal(s.controller.fault,'native_completion_timeout');equal(#s.calls,4)
    s.complete();s.step(10000,'DEPLOY');equal(#s.calls,4);equal(s.count('action_finished'),0)
end)
test('expired pending action does not execute after late native completion',function()
    local s=make();s.step(0);s.step(20,'DEPLOY');s.step(40,'DETONATE');s.step(1600)
    equal(s.controller.pending,nil);s.complete();s.step(2000);equal(#s.calls,4)
end)
test('switching to another weapon cancels pending and never dispatches on return',function()
    local s=make();s.step(0);s.step(20,'DEPLOY');s.step(40,'DETONATE')
    s.u32(s.state+0x1c,1);s.step(100);equal(s.controller.pending,nil)
    s.complete();s.u32(s.state+0x1c,3);s.step(200);equal(#s.calls,4)
end)
test('capture off, loss of focus, mouse input and unavailable data discard pending',function()
    for _,event in ipairs({'capture','focus','mouse','read'}) do
        local s=make();s.step(0);s.step(20,'DEPLOY');s.step(40,'DETONATE')
        if event=='read' then s.memory[s.waddr]=nil end
        s.step(100,nil,event~='capture',event~='focus',event=='mouse')
        equal(s.controller.pending,nil);equal(#s.calls,4)
    end
end)
test('simultaneous test keys do not choose an unverified priority',function()
    local s=make();s.step(0);s.step(20,'BOTH');equal(#s.calls,0)
end)
test('replacement by a vanilla action ends observation without cancelling game state',function()
    local s=make();s.step(0);s.step(20,'DEPLOY');s.step(40,'DETONATE')
    s.u32(s.ability_state,600);s.step(100);equal(#s.calls,4);equal(s.controller.lock,nil)
    equal(s.controller.pending,nil);equal(s.snap().active_ability_id,600)
end)
test('post-call state must prove the requested native lifecycle actually started',function()
    local s=make();s.native.start=function() s.calls[#s.calls+1]={'no_start'} end
    s.step(0);s.step(20,'DETONATE');equal(s.controller.fault,'native_start_not_observed')
    equal(s.count('action_started'),0);s.step(100,'DETONATE');equal(#s.calls,1)
end)
test('snapshot invalidation between request and call prevents native invocation',function()
    local s=make();local _,_,cap=s.snap();s.u32(s.state+0x1c,1)
    equal(pcall(s.backend.execute,'DEPLOY',cap),false);equal(#s.calls,0)
end)
test('code changes after startup are rejected before all native side effects',function()
    local s=make();local _,_,cap=s.snap();s.put(s.signature,'\3\4')
    equal(pcall(s.backend.execute,'DEPLOY',cap),false);equal(#s.calls,0)
end)
test('module and live code mismatch prevent even binding function pointers',function()
    local s=fixture();local n=0;local function bind() n=n+1 end
    s.layout.module_sha256='bad';equal(pcall(backend.new,s.api,reader,base,s.layout,bind),false)
    equal(n,0);s.layout.module_sha256='fixture_hash';s.put(s.signature,'\3\4')
    equal(pcall(backend.new,s.api,reader,base,s.layout,bind),false);equal(n,0)
end)
test('failed logging cannot invoke native gameplay actions',function()
    local s=make();s.step(0);s.log_failure=true
    equal(pcall(s.step,20,'DEPLOY'),false);equal(#s.calls,0)
end)
print('TOTAL '..passed..' action checks; synthetic game data and native calls only')
