local fixture=dofile('tests/contact_fixture.lua')
local function setup()
 local s=fixture();local f=assert(io.open('src/ModeLabels.lua'));local text=f:read('*a');f:close()
 local mod=assert(loadstring('return function(D) '..text..' end'))()(s.D)
 local count=0;s.writes=0;s.original=s.api.read(s.templates+288,88)
 s.writer={text=function(text)count=count+1;return {bytes=string.char(count)..string.rep('\0',7),text=text}end,
 exchange=function(at,expected,value)
  s.writes=s.writes+1
  if s.fail_write==s.writes then return false end
  assert(s.api.read(at,#expected)==expected);s.put(at,value);return true
 end}
 s.labels=mod.new(s.api,s.game,s.base,s.symbols,function()assert(not s.bad_code,'bad code')end,s.writer,s.emit)
 return s
end
local function test(name,fn)fn();print('PASS '..name)end
test('cosmetic mode labels preserve native actions and restore exact original descriptor',function()
 local s=setup();assert(s.labels.sync(true));assert(not s.labels.failed)
 local row,why,cap=s.snap();assert(cap,tostring(why));assert(row.detonation_mode=='MANUAL')
 s.mode('CONTACT');row,why,cap=s.snap();assert(cap and row.detonation_mode=='CONTACT',tostring(why))
 local n=s.writes;s.labels.sync(true);assert(s.writes==n)
 assert(s.labels.stop());assert(s.api.read(s.templates+288,88)==s.original)
 assert(s.api.read(s.game+s.symbols.global_contact_manual_label,16)==string.rep('\0',16))
end)
test('changed ability ID stays rejected even with cosmetic labels installed',function()
 local s=setup();assert(s.labels.sync(true));s.u32(s.templates+288,999)
 local row,why,cap=s.snap();assert(not cap);assert(s.labels.stop());assert(s.base.u32(s.api.read(s.templates+288,4),0)==999)
end)
test('foreign cache slots are never overwritten and partial installation is restored',function()
 local s=setup();local at=s.game+s.symbols.global_contact_contact_label;s.ptr(at,0x999999)
 assert(not s.labels.sync(true));assert(s.labels.failed);assert(s.api.pointer(s.api.read(at,8))==0x999999)
 assert(s.api.read(s.templates+288,88)==s.original)
 assert(s.api.read(s.game+s.symbols.global_contact_manual_label,8)==string.rep('\0',8))
end)
test('every partial write failure restores owned labels and cache pointers',function()
 for i=1,4 do local s=setup();s.fail_write=i;assert(not s.labels.sync(true));assert(s.labels.stop())
 assert(s.api.read(s.templates+288,88)==s.original)
 assert(s.api.read(s.game+s.symbols.global_contact_manual_label,16)==string.rep('\0',16)) end
end)
test('restoration retries a failed write without losing the lease',function()
 local s=setup();assert(s.labels.sync(true));s.fail_write=5;assert(not s.labels.stop());assert(s.labels.lease)
 assert(s.labels.stop());assert(s.api.read(s.templates+288,88)==s.original)
end)
test('label takeover is preserved during cleanup',function()
 local s=setup();assert(s.labels.sync(true));s.u32(s.templates+288+16,12345)
 assert(not s.labels.sync(true));assert(s.base.u32(s.api.read(s.templates+304,4),0)==12345)
end)
test('stale world template is not written during cleanup',function()
 local s=setup();assert(s.labels.sync(true));local n=s.writes;s.ptr(s.owner+s.D.ability_templates,0xdead0000)
 assert(s.labels.stop());assert(s.writes==n+2)
end)
test('changed native code blocks all cosmetic writes',function()
 local s=setup();s.bad_code=true;assert(not s.labels.sync(true));assert(s.writes==0)
end)
test('log failure prevents label installation',function()
 local s=setup();s.log_failure=true;assert(not s.labels.sync(true));assert(s.writes==0)
end)
test('boot managers unavailable waits and installs labels after C4 becomes available',function()
 local s=setup();local R=dofile('private/tests/mock_symbols.lua');local saved=s.api.read(s.game+R.global_mode,8)
 s.zero(s.game+R.global_mode,8)
 for _=1,4 do assert(s.labels.sync(true));assert(not s.labels.failed and s.writes==0)end
 s.put(s.game+R.global_mode,saved);assert(s.labels.sync(true));assert(s.labels.lease and s.writes==4)
 assert(s.labels.stop());assert(s.api.read(s.templates+288,88)==s.original)
end)
test('mission context without selected C4 waits without latching label failure',function()
 local s=setup();local old=s.api.read(s.state+0x1c,4);s.u32(s.state+0x1c,0)
 assert(s.labels.sync(true));assert(not s.labels.failed and s.writes==0)
 s.put(s.state+0x1c,old);assert(s.labels.sync(true));assert(s.labels.lease and s.writes==4)
end)
