local scenario,ffi=dofile('tests/gamepad_entry_fixture.lua')
local base=dofile('src/context_reader.lua')
local passed=0
local function test(name,f)
    local ok,err=pcall(f);package.loaded.ffi=ffi
    assert(ok,name..': '..tostring(err));passed=passed+1;print('PASS '..name)
end
for _,mode in ipairs({0,1}) do
    for _,hz in ipairs({30,60,144}) do
        test('physical mapping and held-edge dedup, mode '..mode..' at '..hz..' Hz',function()
            local s=scenario();s.u32(0x4b000000+16,mode)
            assert(s.module.status=='ready' and s.bound==4 and #s.writes==0)
            s.arm(1/hz);assert(s.flags()==0x148)
            s.button(1,true,1/hz)
            for i=1,hz*2 do if i==math.floor(hz/2) then s.complete() end;s.tick(1/hz) end
            assert(#s.calls==4 and s.calls[1][2]==521 and #s.vanilla==0)
            s.button(1,false,1/hz);s.button(0,true,1/hz)
            for i=1,hz*2 do if i==math.floor(hz/2) then s.complete() end;s.tick(1/hz) end
            assert(#s.calls==5 and s.calls[5][2]==520 and #s.vanilla==0)
            s.button(0,false,1/hz);assert(s.aim_ticks>0,'native Aim unexpectedly swallowed')
            assert(base.u32(s.api.read(0x4b000000+16,4),0)==mode)
            local trace=table.concat(s.lines)
            assert(trace:find('"input":"RMB"',1,true) and trace:find('"input":"LMB"',1,true))
            assert(trace:find('NATIVE_LIFECYCLE_ENDED',1,true) and not trace:find('"record_type":"probe_error"',1,true))
            assert(_G.shutdown()=='shutdown-original' and s.closed and s.flags()==0x1148)
        end)
    end
end
test('simultaneous physical presses invoke Detonate once and never vanilla Deploy',function()
    local s=scenario();s.arm()
    s.mouse[0]={down=true,pressed=true};s.mouse[1]={down=true,pressed=true};s.tick()
    assert(#s.calls==1 and s.calls[1][2]==520 and #s.vanilla==0)
    assert(table.concat(s.lines):find('DETONATE_PRIORITY',1,true))
end)
test('arming while held needs a released baseline and never synthesizes a request',function()
    for _,button in ipairs({0,1}) do
        local s=scenario();s.mouse[button]={down=true,pressed=true};s.arm()
        assert(#s.calls==0 and #s.writes==0)
        s.button(button,false);s.tick();s.button(button,true)
        assert(#s.calls==(button==0 and 1 or 4))
    end
end)
test('F6 disarm during left hold restores only on release without native replay',function()
    local s=scenario();s.arm();s.button(0,true);s.key('f6',true);s.key('f6',false)
    assert(not s.module.capture and s.flags()==0x148 and #s.vanilla==0)
    s.button(0,false);assert(s.flags()==0x1148 and #s.vanilla==0)
    s.button(0,true);assert(#s.vanilla==1 and s.vanilla[1]=='DEPLOY' and #s.calls==1)
end)
test('switching to another weapon restores C4 and passes normal Fire and Aim through',function()
    local s=scenario();s.arm();s.u32(s.state+0x1c,1);s.tick()
    assert(s.flags()==0x1148)
    s.button(0,true);s.button(1,true)
    assert(#s.calls==0 and s.vanilla[1]=='OTHER_WEAPON' and s.aim_ticks>0)
    s.u32(s.state+0x1c,3);s.tick();assert(#s.calls==0 and s.flags()==0x1148)
    s.button(0,false);s.button(1,false);s.tick();s.button(1,true);assert(#s.calls==4)
end)
test('inventory change inside original update restores before the wrapper returns',function()
    local s=scenario();s.arm();s.original_hook=function() s.u32(s.state+0x1c,1) end;s.tick()
    assert(s.flags()==0x1148 and #s.calls==0)
end)
test('menu keys and focus loss disarm, restore and drop queued actions',function()
    for _,key in ipairs({'esc','enter','tab','r','m','focus'}) do
        local s=scenario();s.arm();s.button(1,true);s.button(1,false);s.button(0,true);s.button(0,false)
        if key=='focus' then s.focused=false;s.tick() else s.key(key,true) end
        s.finish();assert(not s.module.capture and s.flags()==0x1148 and #s.calls==4)
    end
end)
test('native refill still gates Deploy while Detonate works with no ready ammo',function()
    local s=scenario();s.arm();s.put(s.rounds_runtime+0x10,'\1');s.u32(s.rounds_state+4,0)
    s.button(1,true);s.button(1,false);assert(#s.calls==0)
    s.button(0,true);s.button(0,false);assert(#s.calls==1 and s.calls[1][2]==520)
    s.finish();s.put(s.rounds_runtime+0x10,'\0');s.u32(s.rounds_state+0x10,55)
    s.button(1,true);assert(#s.calls==5)
end)
test('one pending Deploy retains the original refill behavior without repeat expansion',function()
    local s=scenario();s.u32(s.rounds_state+4,0);s.arm()
    s.button(1,true);s.button(1,false);s.button(1,true);s.button(1,false)
    s.finish();assert(#s.calls==4 and table.concat(s.lines):find('"record_type":"pending_waiting"',1,true))
    s.u32(s.rounds_state+0x10,55);s.put(s.rounds_runtime+0x10,'\0')
    for _=1,12 do s.tick() end
    assert(#s.calls==8);s.finish();assert(#s.calls==8)
end)
test('startup hash or code mismatch performs no memory writes or native binds',function()
    for _,options in ipairs({{bad_hash=true},{bad_code=true}}) do
        local s=scenario(options);assert(s.module.disabled and s.bound==0 and #s.writes==0)
        s.tick();assert(s.updates==1 and #s.calls==0 and s.closed)
    end
end)
test('write failure denies mouse actions; transient restoration failures retry',function()
    local s=scenario();s.fail_writes=true;s.tick();s.key('f6',true)
    assert(s.module.disabled and #s.calls==0 and s.flags()==0x1148)
    s=scenario();s.arm();s.fail_writes=true;s.key('esc',true)
    assert(s.module.disabled and s.flags()==0x148)
    s.fail_writes=false;s.tick();assert(s.flags()==0x1148 and #s.calls==0)
end)
test('read failure blocks actions and restores on recovery',function()
    local s=scenario();s.arm();s.fail_reads=true;s.button(0,true)
    assert(s.module.disabled and #s.calls==0 and s.flags()==0x148)
    s.fail_reads=false;s.button(0,false);assert(s.flags()==0x1148)
end)
test('log write or flush failure restores the gate and denies direct actions',function()
    for _,kind in ipairs({'write','flush'}) do
        local s=scenario();s.arm()
        if kind=='write' then s.log_failure=true elseif kind=='flush' then s.flush_failure=true
        else s.module.records=9999 end
        s.button(1,true);assert(s.module.disabled and #s.calls==0 and s.closed and s.flags()==0x1148)
    end
end)
test('an original update exception is propagated with C4 flags restored',function()
    local s=scenario();s.arm();s.original_error=true
    local ok,why=pcall(s.tick);assert(not ok and tostring(why):find('fixture_original_error',1,true))
    assert(s.flags()==0x1148 and not s.module.capture)
end)
test('guarded native code changing after startup prevents the direct action',function()
    local s=scenario();s.arm();s.bad_code=true;s.button(1,true)
    assert(#s.calls==0 and table.concat(s.lines):find('action_code_changed_',1,true))
    s.button(1,false);s.key('f6',true);assert(s.flags()==0x1148)
end)
test('code changes before enabling prevent acquiring the Fire gate',function()
    local s=scenario();s.bad_code=true;s.key('f6',true)
    assert(s.module.disabled and #s.writes==0 and #s.calls==0 and s.flags()==0x1148)
end)
print('TOTAL '..passed..' EXP04 integration regressions on EXP05; mock Windows/native APIs only')
